// web/src/App.tsx
import { useEffect, useState } from "react";
import { ClientPage } from "./lib/ClientPage";
import { OpusPage } from "./lib/OpusPage";
import { ServerPage } from "./lib/ServerPage";
import "./index.css";

type Page = "client" | "server" | "opus";

function getPageFromHash(hash: string): Page {
  const normalized = hash.replace(/^#/, "");
  if (normalized === "server" || normalized === "opus") {
    return normalized;
  }
  return "client";
}

const pageMeta: Record<Page, { title: string; hint: string }> = {
  client: {
    title: "Client Mode",
    hint: "Use with `make run` to let Python act as the server.",
  },
  server: {
    title: "Server Mode",
    hint: "Use with `make client` to let Python act as the client.",
  },
  opus: {
    title: "Opus Audio",
    hint: "Use with `uvicorn examples.opus_ws:app --reload --port 9001`.",
  },
};

export function App() {
  const [currentPage, setCurrentPage] = useState<Page>(() =>
    typeof window === "undefined" ? "client" : getPageFromHash(window.location.hash),
  );

  useEffect(() => {
    const updatePage = () => {
      setCurrentPage(getPageFromHash(window.location.hash));
    };

    updatePage();
    window.addEventListener("hashchange", updatePage);
    return () => window.removeEventListener("hashchange", updatePage);
  }, []);

  const navigate = (page: Page) => {
    if (window.location.hash.slice(1) !== page) {
      window.location.hash = page;
    }
  };

  const page = pageMeta[currentPage];

  return (
    <div className="app-shell">
      <header className="topbar">
        <div className="topbar__copy">
          <p className="eyebrow">WebRTC Demo</p>
          <h1>{page.title}</h1>
          <p className="hint">{page.hint}</p>
        </div>

        <nav className="nav-tabs" aria-label="Demo modes">
          <button
            type="button"
            className={currentPage === "client" ? "active" : ""}
            onClick={() => navigate("client")}
          >
            Client Mode
          </button>
          <button
            type="button"
            className={currentPage === "server" ? "active" : ""}
            onClick={() => navigate("server")}
          >
            Server Mode
          </button>
          <button
            type="button"
            className={currentPage === "opus" ? "active" : ""}
            onClick={() => navigate("opus")}
          >
            Opus Audio
          </button>
        </nav>
      </header>

      <main className="page-frame">
        {currentPage === "client" ? <ClientPage /> : null}
        {currentPage === "server" ? <ServerPage /> : null}
        {currentPage === "opus" ? <OpusPage /> : null}
      </main>
    </div>
  );
}

export default App;

// web/src/App.svelte
<script lang="ts">
  import ClientPage from "./lib/ClientPage.svelte";
  import ServerPage from "./lib/ServerPage.svelte";
  import OpusPage from "./lib/OpusPage.svelte";

  type Page = "client" | "server" | "opus";
  let currentPage: Page = "client";

  // Simple hash-based routing
  const updatePage = () => {
    const hash = window.location.hash.slice(1);
    if (hash === "server") {
      currentPage = "server";
    } else if (hash === "opus") {
      currentPage = "opus";
    } else {
      currentPage = "client";
    }
  };

  // Initialize on load
  updatePage();
  window.addEventListener("hashchange", updatePage);

  const navigate = (page: Page) => {
    window.location.hash = page;
  };
</script>

<main>
  <nav>
    <h1>WebRTC Demo</h1>
    <div class="nav-links">
      <button
        class:active={currentPage === "client"}
        on:click={() => navigate("client")}
      >
        Client Mode
      </button>
      <button
        class:active={currentPage === "server"}
        on:click={() => navigate("server")}
      >
        Server Mode
      </button>
      <button
        class:active={currentPage === "opus"}
        on:click={() => navigate("opus")}
      >
        Opus Audio
      </button>
    </div>
    <p class="hint">
      {#if currentPage === "client"}
        Use with: <code>make run</code> (Python as server)
      {:else if currentPage === "server"}
        Use with: <code>make client</code> (Python as client)
      {:else}
        Use with: <code>uvicorn examples.opus_ws:app --reload --port 9001</code> (Opus audio server)
      {/if}
    </p>
  </nav>

  {#key currentPage}
    {#if currentPage === "client"}
      <ClientPage />
    {:else if currentPage === "server"}
      <ServerPage />
    {:else if currentPage === "opus"}
      <OpusPage />
    {/if}
  {/key}
</main>

<style>
  main {
    max-width: 800px;
    margin: 0 auto;
    padding: 1rem;
  }

  nav {
    border-bottom: 1px solid #ccc;
    padding-bottom: 1rem;
    margin-bottom: 1rem;
  }

  h1 {
    margin: 0 0 1rem 0;
  }

  .nav-links {
    display: flex;
    gap: 0.5rem;
  }

  .nav-links button {
    padding: 0.5rem 1rem;
    border: 1px solid #ccc;
    background: #f5f5f5;
    cursor: pointer;
    font-size: 1rem;
  }

  .nav-links button:hover {
    background: #e5e5e5;
  }

  .nav-links button.active {
    background: #007bff;
    color: white;
    border-color: #007bff;
  }

  .hint {
    margin-top: 0.5rem;
    font-size: 0.9rem;
    color: #666;
  }

  .hint code {
    background: #f0f0f0;
    padding: 0.2rem 0.4rem;
    border-radius: 3px;
  }
</style>
